<?php

$json = "[
  {
    "response": "ok",
    "data": [
      {
        "": {
          "128141": [
            {
              "id": "1040",
              "customer_id": "800",
              "vendor_id": "128141",
              "customer_order_id": "1873",
              "archive": "proposal",
              "proposal_completed": "2",
              "custome_order_id": "1873",
              "order_product_id": "3550",
              "order_id": "1873",
              "product_id": "49545",
              "order_product_quantity": "1",
              "order_product_name": "نوار\r\nبهداشتی مشبک بزرگ لیدی\r\nکر",
              "order_product_code": "product_49545",
              "order_product_price": "15000.00000",
              "order_product_tax": "0.00000",
              "order_product_tax_info": "",
              "order_product_options": "",
              "order_product_option_parent_id": "0",
              "order_product_status": "",
              "order_product_wishlist_id": "0",
              "order_product_wishlist_product_id": "0",
              "order_product_shipping_id": "",
              "order_product_shipping_method": "",
              "order_product_shipping_price": "0.00000",
              "order_product_shipping_tax": "0.00000",
              "order_product_shipping_params": "",
              "order_product_parent_id": "0",
              "order_product_vendor_price": "0.00000",
              "order_product_params": "",
              "vendor_id_accepted": "128141",
              "user_id": "962"
            }
          ]
        }
      },
      {
        "": {
          "128141": [
            {
              "id": "1040",
              "customer_id": "800",
              "vendor_id": "128141",
              "customer_order_id": "1873",
              "archive": "proposal",
              "proposal_completed": "2",
              "custome_order_id": "1873",
              "order_product_id": "3550",
              "order_id": "1873",
              "product_id": "49545",
              "order_product_quantity": "1",
              "order_product_name": "نوار\r\nبهداشتی مشبک بزرگ لیدی\r\nکر",
              "order_product_code": "product_49545",
              "order_product_price": "15000.00000",
              "order_product_tax": "0.00000",
              "order_product_tax_info": "",
              "order_product_options": "",
              "order_product_option_parent_id": "0",
              "order_product_status": "",
              "order_product_wishlist_id": "0",
              "order_product_wishlist_product_id": "0",
              "order_product_shipping_id": "",
              "order_product_shipping_method": "",
              "order_product_shipping_price": "0.00000",
              "order_product_shipping_tax": "0.00000",
              "order_product_shipping_params": "",
              "order_product_parent_id": "0",
              "order_product_vendor_price": "0.00000",
              "order_product_params": "",
              "vendor_id_accepted": "128141",
              "user_id": "962"
            },
            {
              "id": "1040",
              "customer_id": "800",
              "vendor_id": "128141",
              "customer_order_id": "1873",
              "archive": "proposal",
              "proposal_completed": "2",
              "custome_order_id": "1873",
              "order_product_id": "3551",
              "order_id": "1873",
              "product_id": "49439",
              "order_product_quantity": "1",
              "order_product_name": "نوار\r\nبهداشتی بالدار مشبک 10عددی\r\nنارسیس",
              "order_product_code": "product_49439",
              "order_product_price": "0.00000",
              "order_product_tax": "0.00000",
              "order_product_tax_info": "",
              "order_product_options": "",
              "order_product_option_parent_id": "0",
              "order_product_status": "",
              "order_product_wishlist_id": "0",
              "order_product_wishlist_product_id": "0",
              "order_product_shipping_id": "",
              "order_product_shipping_method": "",
              "order_product_shipping_price": "0.00000",
              "order_product_shipping_tax": "0.00000",
              "order_product_shipping_params": "",
              "order_product_parent_id": "0",
              "order_product_vendor_price": "0.00000",
              "order_product_params": "",
              "vendor_id_accepted": "128141",
              "user_id": "962"
            }
          ]
        }
      },
      {
        "": {
          "128141": [
            {
              "id": "1040",
              "customer_id": "800",
              "vendor_id": "128141",
              "customer_order_id": "1873",
              "archive": "proposal",
              "proposal_completed": "2",
              "custome_order_id": "1873",
              "order_product_id": "3550",
              "order_id": "1873",
              "product_id": "49545",
              "order_product_quantity": "1",
              "order_product_name": "نوار\r\nبهداشتی مشبک بزرگ لیدی\r\nکر",
              "order_product_code": "product_49545",
              "order_product_price": "15000.00000",
              "order_product_tax": "0.00000",
              "order_product_tax_info": "",
              "order_product_options": "",
              "order_product_option_parent_id": "0",
              "order_product_status": "",
              "order_product_wishlist_id": "0",
              "order_product_wishlist_product_id": "0",
              "order_product_shipping_id": "",
              "order_product_shipping_method": "",
              "order_product_shipping_price": "0.00000",
              "order_product_shipping_tax": "0.00000",
              "order_product_shipping_params": "",
              "order_product_parent_id": "0",
              "order_product_vendor_price": "0.00000",
              "order_product_params": "",
              "vendor_id_accepted": "128141",
              "user_id": "962"
            },
            {
              "id": "1040",
              "customer_id": "800",
              "vendor_id": "128141",
              "customer_order_id": "1873",
              "archive": "proposal",
              "proposal_completed": "2",
              "custome_order_id": "1873",
              "order_product_id": "3551",
              "order_id": "1873",
              "product_id": "49439",
              "order_product_quantity": "1",
              "order_product_name": "نوار\r\nبهداشتی بالدار مشبک 10عددی\r\nنارسیس",
              "order_product_code": "product_49439",
              "order_product_price": "0.00000",
              "order_product_tax": "0.00000",
              "order_product_tax_info": "",
              "order_product_options": "",
              "order_product_option_parent_id": "0",
              "order_product_status": "",
              "order_product_wishlist_id": "0",
              "order_product_wishlist_product_id": "0",
              "order_product_shipping_id": "",
              "order_product_shipping_method": "",
              "order_product_shipping_price": "0.00000",
              "order_product_shipping_tax": "0.00000",
              "order_product_shipping_params": "",
              "order_product_parent_id": "0",
              "order_product_vendor_price": "0.00000",
              "order_product_params": "",
              "vendor_id_accepted": "128141",
              "user_id": "962"
            },
            {
              "id": "1040",
              "customer_id": "800",
              "vendor_id": "128141",
              "customer_order_id": "1873",
              "archive": "proposal",
              "proposal_completed": "2",
              "custome_order_id": "1873",
              "order_product_id": "3552",
              "order_id": "1873",
              "product_id": "49619",
              "order_product_quantity": "1",
              "order_product_name": "نوار\r\nبهداشتی متوسط 10عددی لیدی\r\nکر",
              "order_product_code": "product_49619",
              "order_product_price": "0.00000",
              "order_product_tax": "0.00000",
              "order_product_tax_info": "",
              "order_product_options": "",
              "order_product_option_parent_id": "0",
              "order_product_status": "",
              "order_product_wishlist_id": "0",
              "order_product_wishlist_product_id": "0",
              "order_product_shipping_id": "",
              "order_product_shipping_method": "",
              "order_product_shipping_price": "0.00000",
              "order_product_shipping_tax": "0.00000",
              "order_product_shipping_params": "",
              "order_product_parent_id": "0",
              "order_product_vendor_price": "0.00000",
              "order_product_params": "",
              "vendor_id_accepted": "128141",
              "user_id": "962"
            }
          ]
        }
      }
    ]
  },
  null
]";

echo json_decode($json);