let obj =[
  {
      "response": "ok",
      "data": [
          {
              "done": {
                  "128141": [
                      {
                          "id": "1076",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1904",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1904",
                          "order_product_id": "3604",
                          "order_id": "1904",
                          "product_id": "49264",
                          "order_product_quantity": "1",
                          "order_product_name": "شامپو بدن لوکس آلبالو 250+ یک عدد رایگان",
                          "order_product_code": "product_49264",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      },
                      {
                          "id": "1076",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1904",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1904",
                          "order_product_id": "3605",
                          "order_id": "1904",
                          "product_id": "49109",
                          "order_product_quantity": "1",
                          "order_product_name": "پک شامپو بدن 400 گرمی + 280 گرمی گلرنگ",
                          "order_product_code": "product_49109",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      },
                      {
                          "id": "1076",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1904",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1904",
                          "order_product_id": "3606",
                          "order_id": "1904",
                          "product_id": "49441",
                          "order_product_quantity": "1",
                          "order_product_name": "شامپو ویتامینه 400 میل گلان",
                          "order_product_code": "product_49441",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "done": {
                  "128141": [
                      {
                          "id": "1084",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1910",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1910",
                          "order_product_id": "3614",
                          "order_id": "1910",
                          "product_id": "10132",
                          "order_product_quantity": "1",
                          "order_product_name": " سرخ کردنی گلناز",
                          "order_product_code": "product_10132",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "done": {
                  "128141": [
                      {
                          "id": "1100",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1919",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1919",
                          "order_product_id": "3624",
                          "order_id": "1919",
                          "product_id": "17478",
                          "order_product_quantity": "1",
                          "order_product_name": "تراش بولت",
                          "order_product_code": "product_17478",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "done": {
                  "128141": [
                      {
                          "id": "1104",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1921",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1921",
                          "order_product_id": "3626",
                          "order_id": "1921",
                          "product_id": "8503",
                          "order_product_quantity": "1",
                          "order_product_name": "خیار شور ویژه 700 گرمی شیشه ای برتر",
                          "order_product_code": "product_8503",
                          "order_product_price": "70000.00000",
                          "order_product_tax": "6300.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:6300;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "done": {
                  "128141": [
                      {
                          "id": "1108",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1923",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1923",
                          "order_product_id": "3628",
                          "order_id": "1923",
                          "product_id": "49191",
                          "order_product_quantity": "1",
                          "order_product_name": "پوشک پرمیوم 8-16کیلوگرم 34 عددی مای بیبی",
                          "order_product_code": "product_49191",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "done": {
                  "128141": [
                      {
                          "id": "1116",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1927",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1927",
                          "order_product_id": "3632",
                          "order_id": "1927",
                          "product_id": "1113",
                          "order_product_quantity": "1",
                          "order_product_name": " ویفر شکلاتی با مغز فندق گرجی",
                          "order_product_code": "product_1113",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      },
                      {
                          "id": "1116",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1927",
                          "buy_status": "done",
                          "archive": "1",
                          "proposal_completed": "1",
                          "custome_order_id": "1927",
                          "order_product_id": "3633",
                          "order_id": "1927",
                          "product_id": "9294",
                          "order_product_quantity": "1",
                          "order_product_name": " شکلات ساندرا گل با طعم کارامل چیچک",
                          "order_product_code": "product_9294",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": null,
                          "vendor_id_accepted": "128141",
                          "user_id": null,
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "proposal": {
                  "128141": [
                      {
                          "id": "1088",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1912",
                          "buy_status": "proposal",
                          "archive": "1",
                          "proposal_completed": "-1",
                          "custome_order_id": "1912",
                          "order_product_id": "3603",
                          "order_id": "1912",
                          "product_id": "9038",
                          "order_product_quantity": "1",
                          "order_product_name": " سوپ جو سبزان",
                          "order_product_code": "product_9038",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "'",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      },
                      {
                          "id": "1088",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1912",
                          "buy_status": "proposal",
                          "archive": "1",
                          "proposal_completed": "-1",
                          "custome_order_id": "1912",
                          "order_product_id": "3604",
                          "order_id": "1912",
                          "product_id": "9036",
                          "order_product_quantity": "1",
                          "order_product_name": "فلافل 400 گرمی مام",
                          "order_product_code": "product_9036",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "'",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "proposal": {
                  "128141": [
                      {
                          "id": "1092",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1915",
                          "buy_status": "proposal",
                          "archive": "1",
                          "proposal_completed": "-1",
                          "custome_order_id": "1915",
                          "order_product_id": "3605",
                          "order_id": "1915",
                          "product_id": "10253",
                          "order_product_quantity": "1",
                          "order_product_name": " پنیر سفید تازه",
                          "order_product_code": "product_10253",
                          "order_product_price": "0.00000",
                          "order_product_tax": "5850.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:5850;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "proposal": {
                  "128141": [
                      {
                          "id": "1120",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1930",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1930",
                          "order_product_id": "3612",
                          "order_id": "1930",
                          "product_id": "1009",
                          "order_product_quantity": "1",
                          "order_product_name": " بیسکویت و ویفر فرمند",
                          "order_product_code": "product_1009",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "'",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ]
              }
          },
          {
              "proposal": {
                  "128141": [
                      {
                          "id": "1128",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1934",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1934",
                          "order_product_id": "3617",
                          "order_id": "1934",
                          "product_id": "9319",
                          "order_product_quantity": "2",
                          "order_product_name": " پف پفی نارگیلی 50 گرمی شیبا",
                          "order_product_code": "product_9319",
                          "order_product_price": "25000.00000",
                          "order_product_tax": "810.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:810;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      },
                      {
                          "id": "1128",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1934",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1934",
                          "order_product_id": "3618",
                          "order_id": "1934",
                          "product_id": "10133",
                          "order_product_quantity": "1",
                          "order_product_name": " سرخ کردنی گلناز",
                          "order_product_code": "product_10133",
                          "order_product_price": "186000.00000",
                          "order_product_tax": "16740.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:16740;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ],
                  "129308": [
                      {
                          "id": "1127",
                          "customer_id": "800",
                          "vendor_id": "129308",
                          "customer_order_id": "1934",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1934",
                          "order_product_id": "3619",
                          "order_id": "1934",
                          "product_id": "9453",
                          "order_product_quantity": "2",
                          "order_product_name": "شکلات رومیتا ۲۰۰ گرمی فرمند",
                          "order_product_code": "product_9453",
                          "order_product_price": "220000.00000",
                          "order_product_tax": "13050.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:13050;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "129308",
                          "user_id": "962",
                          "ShopName": "rr"
                      },
                      {
                          "id": "1127",
                          "customer_id": "800",
                          "vendor_id": "129308",
                          "customer_order_id": "1934",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1934",
                          "order_product_id": "3620",
                          "order_id": "1934",
                          "product_id": "9317",
                          "order_product_quantity": "2",
                          "order_product_name": " بستنی زمستانی 17 گرمی شیبا",
                          "order_product_code": "product_9317",
                          "order_product_price": "9000.00000",
                          "order_product_tax": "810.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:810;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "129308",
                          "user_id": "1975",
                          "ShopName": "rr"
                      },
                      {
                          "id": "1127",
                          "customer_id": "800",
                          "vendor_id": "129308",
                          "customer_order_id": "1934",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1934",
                          "order_product_id": "3621",
                          "order_id": "1934",
                          "product_id": "10133",
                          "order_product_quantity": "1",
                          "order_product_name": " سرخ کردنی گلناز",
                          "order_product_code": "product_10133",
                          "order_product_price": "186000.00000",
                          "order_product_tax": "16740.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:16740;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "129308",
                          "user_id": "1975",
                          "ShopName": "rr"
                      },
                      {
                          "id": "1127",
                          "customer_id": "800",
                          "vendor_id": "129308",
                          "customer_order_id": "1934",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1934",
                          "order_product_id": "3622",
                          "order_id": "1934",
                          "product_id": "9453",
                          "order_product_quantity": "2",
                          "order_product_name": "شکلات رومیتا ۲۰۰ گرمی فرمند",
                          "order_product_code": "product_9453",
                          "order_product_price": "220000.00000",
                          "order_product_tax": "13050.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:13050;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "129308",
                          "user_id": "1975",
                          "ShopName": "rr"
                      }
                  ]
              }
          },
          {
              "proposal": {
                  "128141": [
                      {
                          "id": "1132",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1938",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1938",
                          "order_product_id": "3623",
                          "order_id": "1938",
                          "product_id": "49301",
                          "order_product_quantity": "2",
                          "order_product_name": "گیلاس میولند",
                          "order_product_code": "product_49301",
                          "order_product_price": "295000.00000",
                          "order_product_tax": "6300.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:6300;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      },
                      {
                          "id": "1132",
                          "customer_id": "800",
                          "vendor_id": "128141",
                          "customer_order_id": "1938",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1938",
                          "order_product_id": "3624",
                          "order_id": "1938",
                          "product_id": "8502",
                          "order_product_quantity": "1",
                          "order_product_name": "خیار شور ممتاز 700 گرمی شیشه ای برتر",
                          "order_product_code": "product_8502",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "'",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "128141",
                          "user_id": "962",
                          "ShopName": "فروشگاه دارای بازاریاب 11"
                      }
                  ],
                  "129308": [
                      {
                          "id": "1131",
                          "customer_id": "800",
                          "vendor_id": "129308",
                          "customer_order_id": "1938",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1938",
                          "order_product_id": "3625",
                          "order_id": "1938",
                          "product_id": "49302",
                          "order_product_quantity": "2",
                          "order_product_name": "انگور میولند",
                          "order_product_code": "product_49302",
                          "order_product_price": "105000.00000",
                          "order_product_tax": "6300.00000",
                          "order_product_tax_info": "a:1:{s:13:\"0000_00000001\";O:8:\"stdClass\":19:{s:11:\"taxation_id\";s:1:\"1\";s:12:\"zone_namekey\";a:1:{i:0;s:16:\"country_Iran_101\";}s:16:\"category_namekey\";s:11:\"default_tax\";s:11:\"tax_namekey\";s:21:\"ارزش افزوده\";s:18:\"taxation_published\";s:1:\"1\";s:13:\"taxation_type\";s:0:\"\";s:15:\"taxation_access\";s:3:\"all\";s:19:\"taxation_cumulative\";s:1:\"0\";s:18:\"taxation_post_code\";s:0:\"\";s:19:\"taxation_date_start\";s:1:\"0\";s:17:\"taxation_date_end\";s:1:\"0\";s:22:\"taxation_internal_code\";s:0:\"\";s:13:\"taxation_note\";s:0:\"\";s:16:\"taxation_site_id\";s:0:\"\";s:17:\"taxation_ordering\";s:1:\"0\";s:8:\"tax_rate\";s:7:\"0.09000\";s:9:\"zone_type\";s:7:\"country\";s:9:\"tax_ratio\";i:1;s:10:\"tax_amount\";d:6300;}}",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "129308",
                          "user_id": "1975",
                          "ShopName": "rr"
                      },
                      {
                          "id": "1131",
                          "customer_id": "800",
                          "vendor_id": "129308",
                          "customer_order_id": "1938",
                          "buy_status": "proposal",
                          "archive": null,
                          "proposal_completed": "2",
                          "custome_order_id": "1938",
                          "order_product_id": "3626",
                          "order_id": "1938",
                          "product_id": "8502",
                          "order_product_quantity": "1",
                          "order_product_name": "خیار شور ممتاز 700 گرمی شیشه ای برتر",
                          "order_product_code": "product_8502",
                          "order_product_price": "0.00000",
                          "order_product_tax": "0.00000",
                          "order_product_tax_info": "'",
                          "order_product_options": "",
                          "order_product_option_parent_id": "0",
                          "order_product_status": "",
                          "order_product_wishlist_id": "0",
                          "order_product_wishlist_product_id": "0",
                          "order_product_shipping_id": "",
                          "order_product_shipping_method": "",
                          "order_product_shipping_price": "0.00000",
                          "order_product_shipping_tax": "0.00000",
                          "order_product_shipping_params": "",
                          "order_product_parent_id": "0",
                          "order_product_vendor_price": "0.00000",
                          "order_product_params": "",
                          "vendor_id_accepted": "129308",
                          "user_id": "1975",
                          "ShopName": "rr"
                      }
                  ]
              }
          }
      ]
  },
  null
]

obj[0].data.forEach(function(value,index){
  //show order status
  let status = (Object.keys(value)[0])
  let vendor_id = ([Object.keys(value[Object.keys(value)[0]])[0]][0])
  console.log(value[status][vendor_id][0]['order_id'])
  // console.log([Object.keys(value[Object.keys(value)[0]])[0]][0])
})